<#
.SYNOPSIS
    Promotes the TAK Server admin certificate to the administrator role via SSH.

.DESCRIPTION
    Automates the procedure defined in promoteAdmin.sh against a remote TAK
    Server host over an established Posh-SSH session.

    Steps performed:
      1. Run UserManager.jar certmod -A admin.pem to grant the admin certificate
         the TAK Server administrator role.
      2. Restart takserver and wait for the service to become active.
      3. Copy admin.p12 to /home/atak/ and set ownership to the atak user.

    Must be run after New-TAKServerCertificate has completed successfully.
    After this step, install /opt/tak/certs/files/admin.p12 into your browser
    as a user certificate to access the TAK Server WebUI as an administrator.

.PARAMETER SshSession
    An active Posh-SSH SSH session to the target TAK Server host.

.PARAMETER ServiceRestartTimeout
    Maximum seconds to wait for takserver to become active after the restart.
    Defaults to 300.

.EXAMPLE
    PS> $sess = New-SSHSession -ComputerName '192.168.1.50' -Credential (Get-Credential)
    PS> Set-TAKAdminCertificate -SshSession $sess

    Promotes the admin certificate generated by New-TAKServerCertificate.

.EXAMPLE
    PS> Set-TAKAdminCertificate -SshSession $sess -ServiceRestartTimeout 600 -Verbose

    Same as above with verbose output and a longer service wait timeout.

.OUTPUTS
    None

.NOTES
    Requires the Posh-SSH module: Install-Module Posh-SSH -Scope CurrentUser
    Run after New-TAKServerCertificate. The admin.p12 file is placed at
    /home/atak/admin.p12 and must be distributed securely to the administrator.
#>
function Set-TAKAdminCertificate {
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
    param (
        [Parameter(Mandatory)]
        [SSH.SshSession] $SshSession,

        [Parameter()]
        [ValidateRange(60, 600)]
        [int] $ServiceRestartTimeout = 300
    )

    if (-not $PSCmdlet.ShouldProcess($SshSession.Host, 'Promote admin certificate to TAK Server administrator role')) {
        return
    }

    # ── 1. Promote admin.pem to administrator ──────────────────────────────
    Write-Progress -Activity 'Setting TAK admin certificate' -Status 'Promoting admin.pem' -PercentComplete 20
    Invoke-TAKRemoteCommand -Session $SshSession -Description 'Promote admin.pem to administrator role' -Command `
        'sudo java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/admin.pem'

    # ── 2. Restart takserver ───────────────────────────────────────────────
    Write-Progress -Activity 'Setting TAK admin certificate' -Status 'Restarting takserver' -PercentComplete 45
    Invoke-TAKRemoteCommand -Session $SshSession -Description 'Restart takserver' -Command `
        'sudo systemctl restart takserver'

    Wait-TAKServiceReady -Session $SshSession -ServiceName 'takserver' -TimeoutSeconds $ServiceRestartTimeout

    # ── 3. Copy admin.p12 to /home/atak/ ──────────────────────────────────
    Write-Progress -Activity 'Setting TAK admin certificate' -Status 'Copying admin.p12 to /home/atak/' -PercentComplete 85
    Invoke-TAKRemoteCommand -Session $SshSession -Description 'Copy admin.p12 and set ownership' -Command @'
sudo cp /opt/tak/certs/files/admin.p12 /home/atak/
sudo chown atak:atak /home/atak/admin.p12
sudo chmod 640 /home/atak/admin.p12
'@

    Write-Progress -Activity 'Setting TAK admin certificate' -Completed
    Write-Verbose 'Admin certificate promotion complete.'
    Write-Verbose 'Retrieve /home/atak/admin.p12 and install it in your browser to access the TAK Server WebUI.'
}
