title: DigitalTAK
tagline: "TAK Server 5.7 automation for Rocky Linux 9 on Hyper-V"
description: "Automated CivTAK deployment and management for Rocky Linux 9 on Hyper-V"
lang: en-GB
baseurl: ""
url: "https://digitaltak.lukeleigh.com"

author:
  name: "Luke Leigh"
  url: https://github.com/BanterBoy

version: 1.0

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
